"""proverb table

Revision ID: 26d8a2c37aee
Revises: 5a15cc60146e
Create Date: 2021-07-05 21:26:05.774348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d8a2c37aee'
down_revision = '5a15cc60146e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proverbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proverb', sa.String(length=300), nullable=False),
    sa.Column('translation', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proverb')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proverbs')
    # ### end Alembic commands ###
